---
- name: "Update apt"
  apt:
    update_cache: yes
  become: true
              
- name: "Install prerequisites"
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - "apt-transport-https"
    - "ca-certificates"
    - "curl"
    - "software-properties-common"
    - "linux-image-extra-{{ ansible_kernel }}"
    - "linux-image-extra-virtual"
    - "python-pip"
  become: true

- name: "Install docker-py"
  become: true
  pip:
    name: "docker-py"
    state: latest
      
- name: "Add Docker apt key"
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present
  register: add_repository_key
  ignore_errors: true
  become: true

- name: "Add Docker apt key"
  shell: "curl -sSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -"
  args:
    warn: no
  when: add_repository_key|failed
    
- name: "Add docker apt repo"
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_lsb.codename}} stable"
    update_cache: yes
  become: true
    
- name: "Install Docker apt package"
  apt:
    name: "docker-ce"
    state: latest
    update_cache: yes
  become: true
    
- name: "Ensure Docker service is installed and restarted"
  service:
    name: docker
    state: restarted
    enabled: yes
  become: true
    
- name: "Adding user {{ ansible_user }} to docker group"
  user:
    name: "{{ ansible_user }}"
    group: "docker"
    append: "yes"
  become: true